services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${URL_DB}
      - SPRING_DATASOURCE_USERNAME=${USERNAME_DB}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD_DB}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=false
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true