spring.datasource.url=${URL_HOMOLOG_DB}
spring.datasource.username=${USERNAME_HOMOLOG_DB}
spring.datasource.password=${PASSWORD_HOMOLOG_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true