spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Otimizações de Memória e Conexões (Produção)
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=4
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.jpa.open-in-view=false
spring.main.lazy-initialization=true